INSERT INTO student VALUES
(1, 'ANTAL IOAN'),
(2, 'AVRAM STEFAN'),
(3, 'AVRAMOVIC TAMARA'),
(4, 'BABUSCOV_EDUARD'),
(5, 'BOGDAN CRISTIAN VLAD'),
(6, 'BORONTIS GABRIELA ELENA'),
(7, 'BUDA DACIAN'),
(8, 'BUFU MARIO'),
(9, 'Banarescu Cristian'),
(10, 'Bratulescu Mihai'),
(11, 'CAPATINA IRINA CRISTINA'),
(12, 'CIOLOCA LAVINIA'),
(13, 'CONSTANTIN HORIA'),
(14, 'COVATARIU LARISA-CRISTINA'),
(15, 'Carla Lazar'),
(16, 'Costea Lucian'),
(17, 'DIC DANIEL'),
(18, 'Dunca Ciprian'),
(19, 'GUGEA OANA'),
(20, 'Gainar Iulian'),
(21, 'Groza Beniamin'),
(22, 'HEIDELBACHER ANDREI'),
(23, 'HODUT RIANA'),
(24, 'IANCU VICTOR'),
(25, 'IOCSA VALERIU IONUT'),
(26, 'LATES RAZVAN'),
(27, 'Lasak Vladko'),
(28, 'Lica Sorin'),
(29, 'MICLEA RALUCA'),
(30, 'MORAR MIRABELA-ROXANA'),
(31, 'PEPTAN ALEX'),
(32, 'PREJBAN DANIEL'),
(33, 'RADULESCU VLAD'),
(34, 'RibanaCerbulescu'),
(35, 'SALCIANU OCTAVIAN'),
(36, 'Sebastian Octavian Sas'),
(37, 'TEUDAN ADINA'),
(38, 'TRONCOTA DENIS'),
(39, 'ribanacerbulescu');
