create table student(ID INTEGER NOT NULL,
    Name VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID));

create table file (ID INTEGER NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    Date VARCHAR(25) NOT NULL,
    IP VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID));

create table ftplog (ID INTEGER NOT NULL,
    StudentID INTEGER NOT NULL,
    FileID INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (StudentID) REFERENCES student(ID),
    FOREIGN KEY (FileID) REFERENCES file(ID));